### ISSUE TITLE
Calc and Replace doesn't work if in the middle of line.

### ISSUE THREAD

**Issue by NickGrease** [weirongxu/vscode-calc#2]
Version: 1.41.0-insider (system setup)
Commit: d386b49dee6267238389c0a616af2be89726a4e3
Date: 2019-12-06T12:19:08.526Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

ex.
`"x1":521,"y1":444,"x2":591,"y2":500,"rows":2,"cols":2,"rowHeight":28,"columWidth":35})`

The line above, trying to change "y2" to 500+65 doesn't work if I use the palette command 'Calculate and Replace'. If I delete everything after '500' the palette command 'Calculate and Replace' works.

Ideally I'd like to not use the palette, simply typing '500+65=' brings up the auto-complete and hitting enter/tab inserts the answer, but with the preference setting `calc.replaceOriginalExpression: true` it should replace the expression (even if its in the middle of the line). Currently it does not.

P.S. Thanks for the extension, very useful when working with positioning UI elements

P.P.S The language I'm currently using is AutoHotKey. I'm using `https://github.com/vinnyjames/vscode-autohotkey` and `https://github.com/Denis-net/vscode-ahk-manager` for code completion and highlighting if that could make a difference.

**Comment by weirongxu** [comment]
Use `Calculate and append in front of cursor` instead of `Calculate and Replace`
