### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [weirongxu/vscode-calc#6]
The [Open VSX Registry](https://open-vsx.org/?search=calc) does not include a calculator extension so far. It would be good to hae this extension available as it seems to be handy for some tasks.

Thank you for considering this.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by weirongxu** [comment]
https://open-vsx.org/extension/raidou/calc
